apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name:  ${{ values.app_name }}
  description: Hello Worldサービスです
  labels:
    app: ${{ values.app_name }}
  links:
    - url: https://console-openshift-console.apps.rosa.sb961-hcp.611c.p3.openshiftapps.com/k8s/cluster/projects/${{ values.app_name }}
      title: OpenShift Console
      icon: dashboard
    - url: https://${{ values.app_name }}-${{ values.app_name }}.apps.rosa.sb961-hcp.611c.p3.openshiftapps.com
      title: Application Web Site
      icon: dashboard
    - url: https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.git_repo_name }} 
      title: App Repository
      icon: github
  annotations:
    backstage.io/kubernetes-label-selector: 'app=${{ values.app_name }}'
    backstage.io/kubernetes-namespace: ${{ values.app_name }}
spec:
  type: website
  owner: ${{ values.owner }}
  lifecycle: production
